export const APP_AUTH_CONST = "AuthUser"
export const SingUpMessage = "Thank you, your registration successfull"
export const LogInMessage = "Log in session successfull"
export const LogOutMessage = "Log out successfull"
export const NullResponseErrorMessage  = "Something went wrong!"